# #Problem 2: The TargetServer Class (Updating State)

# class targetserver():
#     def __init__(self,ip_address):
#         self.ip_address = ip_address
#         self.status = 'offline'

#     def go_online(self):
#         self.status = 'online'

    

# my_target = [targetserver('127.0.0.1'), targetserver('192.168.1.1')]
# my_target[0].go_online()
# print(f"server {my_target[0].ip_address} is now {my_target[0].status}!")



